import { AxiosClient } from '@/axios';
import Loading from '@/components/ui/Loading';
import CityWeather from '@/components/weatherDetail/CityWeather';
import IWeather from '@/types/IWeather';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import React, { Suspense } from 'react';
import { Typography } from '@mui/material';
import Video from '@/components/weatherDetail/Video';

const CityPage: React.FC<{ cityWeatherResponse: IWeather }> = ({ cityWeatherResponse }) => {
  return (
    <React.Fragment>
      <Head>
        <title>Weather App - {cityWeatherResponse.city.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Video rawDescription={cityWeatherResponse.list[0].weather[0].description} />
      <Suspense fallback={<Typography variant="h1">Loading...</Typography>}>
        <CityWeather cityWeatherResponse={cityWeatherResponse} />
      </Suspense>
    </React.Fragment>
  );
};

export default CityPage;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const params = context.params?.cityName;

  const cityWeatherResponse = await AxiosClient.get(`/api/city/${params}`).then((res) => res.data);
  return {
    props: {
      cityWeatherResponse
    }
  };
};
