import SearchBar from '@/components/searchBar/SearchBar';
import Head from 'next/head';
import { Container, Grid, Slider } from '@mui/material';

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container>
        <Grid item xs={12}>
          <SearchBar />
        </Grid>
      </Grid>
    </Container>
  );
}
