import SearchBar from '@/components/searchBar/SearchBar';
import { Container, Grid, useMediaQuery } from '@mui/material';
import { useTheme } from '@mui/material/styles';
import Head from 'next/head';

export default function Home() {
  const themePage = useTheme();
  const isMobile = useMediaQuery(themePage.breakpoints.down('md'));

  return (
    <Container>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <img
        src={isMobile ? '/background-mobile.jpg' : '/background.jpg'}
        alt=""
        width={100}
        height={100}
        style={{
          position: 'fixed',
          right: 0,
          bottom: 0,
          minWidth: '100%',
          minHeight: '100%',
          zIndex: -1,
          opacity: 0.8
        }}
      />

      <Grid container>
        <Grid
          item
          className={isMobile ? 'flex justify-center mt-20' : 'flex justify-center mt-24'}
          xs={12}>
          <SearchBar />
        </Grid>
      </Grid>
    </Container>
  );
}
